POST http://localhost:3000/api/categorias/
Content-Type : application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzMzMjgyNjM3LCJleHAiOjE3MzMyODYyMzd9.n5VwFUQ4fweQpTg6la3HFHksRd4UvuLtHS68RF-VX5s

{
    "name":"Terror"
} 